version: '2'

services:
  3proxy:
    image: manhnv56/3proxy
    container_name: 3proxy
    restart: always
    environment:
      - HTTP_PORT=3130
      - SOCKS_PORT=1081
    volumes:
       - ./passwd:/etc/3proxy/passwd:ro
    ports:
      - "1081:1081"
      - "3130:3130"
